'''
Created on Jan 24, 2022

@author: Dream Machines
'''

# MIDI CC
MIDI_CC_SHIFT                      = 95
MIDI_CC_ENTER_SAVE_MODE            = 53
MIDI_CC_RESET_PRESET               = 54
MIDI_CC_PREV_ACTIVE_FX_UNIT_PRESET = 55
MIDI_CC_NEXT_ACTIVE_FX_UNIT_PRESET = 56
MIDI_CC_EFFECTS_PAGE_1             = 49
MIDI_CC_EFFECTS_PAGE_2             = 50
MIDI_CC_EFFECTS_PAGE_3             = 51
MIDI_CC_EFFECTS_PAGE_4             = 52

MIDI_CC_EFFECT_1              = 49
MIDI_CC_EFFECT_2              = 50
MIDI_CC_EFFECT_3              = 51
MIDI_CC_EFFECT_4              = 52
MIDI_CC_EFFECT_5              = 53
MIDI_CC_EFFECT_6              = 54
MIDI_CC_EFFECT_7              = 55
MIDI_CC_EFFECT_8              = 56

MIDI_CC_SYNTH_VOLUME          = 93
MIDI_CC_FX_LEVEL              = 93

MIDI_CC_TURNADO_DICTATOR      = 94
MIDI_CC_TURNADO_DRY_WET       = 94
MIDI_CC_TURNADO_RANDOMIZE     = 95

MIDI_CC_TURNADO_PREV_PRESET   = 36
MIDI_CC_TURNADO_NEXT_PRESET   = 37
MIDI_CC_TURNADO_ON_OFF        = 38
MIDI_CC_CHANGE_ACTIVE_FX_UNIT = 39

MIDI_CC_EFFECT_PARAM_1        = 70
MIDI_CC_EFFECT_PARAM_2        = 71
MIDI_CC_EFFECT_PARAM_3        = 72
MIDI_CC_EFFECT_PARAM_4        = 73
MIDI_CC_EFFECT_PARAM_5        = 74
MIDI_CC_EFFECT_PARAM_6        = 75
MIDI_CC_EFFECT_PARAM_7        = 76
MIDI_CC_EFFECT_PARAM_8        = 77

# ROUTING
# ...

# CONSTANTS

ENTER_MIDI_MAPPING_SAVE_MODE_SHIFT = 1000

KP3_PLUS_ABCD_PRESSED         = 100
KP3_PLUS_ABCD_RELEASED        = 64

NUMBER_OF_FX_IN_PAGE          = 8

FINISHER_VOODOO_MODE_NUMBER   = 50

DEFAULT_TURNADO_DRY_WET_LEVEL = 0.5

MIDI_CC_INTERNAL_LOOP         = 123

PERSISTENCY_CURRENT_VERSION          = 1.0
PERSISTENCY_VERSION_KEY              = "VERSION"
PERSISTENCY_PLUGIN_PARAMETERS_KEY    = "PLUGIN_PARAMS"
PERSISTENCY_ACTIVE_FX_UNIT_KEY       = "ACTIVE_FX_UNIT"
PERSISTENCY_MIDI_MAPPING_KEY         = "MIDI_MAPPING"

MIN_PLUGIN_NUMBER = 0
MAX_PLUGIN_NUMBER = 9

# MASTER MIXER SLOT INDICES
MIDI_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 0
SYNTH_CONTROL_SURFACE_MIXER_SLOT_INDEX = 1

# MIXER SLOT INDICES
FABFILTER_PRO_Q3_SLOT_INDEX    = 0
FINISHER_VOODOO_SLOT_INDEX     = 1
MANIPULATOR_SLOT_INDEX         = 2
FAST_DIST_SLOT_INDEX           = 3
STEREO_ENHANCER_SLOT_INDEX     = 4
REVERB_SLOT_INDEX              = 5
DELAY_SLOT_INDEX               = 6
FRUITY_FILTER_SLOT_INDEX       = 7
COMPRESSOT_SLOT_INDEX          = 8
LIMITER_SLOT_INDEX             = 9
FX_ACTIVATION_STATE_SLOT_INDEX = 10

TURNADO_SLOT_INDEX             = 0

NO_ADJUSTABLE_EFFECT_AVAILABLE = -1

PRESET_CHANGE_PROTECTOR_PANOMATIC_SLOT_INDEX = 9

# PARAMS LIMITS
FABFILTER_PRO_Q3_PARAMS_LIMIT = 360
FINISHER_VOODOO_PARAMS_LIMIT  = 10
MANIPULATOR_PARAMS_LIMIT      = 200
TURNADO_PARAMS_LIMIT          = 4000

# PLUGIN PARAMETERS
PANOMATIC_VOLUME_PARAM_INDEX = 1

FINISHER_VOODOO_MODE_PARAM_INDEX   = 2
FINISHER_VOODOO_EFFECT_PARAM_INDEX = 3
FINISHER_VOODOO_VARIATION_1_PARAM_INDEX = 4
FINISHER_VOODOO_VARIATION_2_PARAM_INDEX = 5
FINISHER_VOODOO_VARIATION_3_PARAM_INDEX = 6
FINISHER_VOODOO_VARIATION_4_PARAM_INDEX = 7

MANIPULATOR_FORMANT_PARAM_INDEX    = 0
MANIPULATOR_PITCH_PARAM_INDEX      = 1
MANIPULATOR_RATIO_PARAM_INDEX      = 2
MANIPULATOR_HARMONICS_PARAM_INDEX  = 3
MANIPULATOR_FM_PARAM_INDEX         = 4
MANIPULATOR_ALTERNATOR_PARAM_INDEX = 5
MANIPULATOR_OCTAVE_PARAM_INDEX     = 6
MANIPULATOR_WETDRY_PARAM_INDEX     = 7

TURNADO_DICTATOR_PARAM_INDEX       = 8
TURNADO_DRY_WET_PARAM_INDEX        = 9
TURNADO_RANDOMIZE_PARAM_INDEX      = 10

TURNADO_NEXT_PRESET_PARAM_INDEX    = 8
TURNADO_PREV_PRESET_PARAM_INDEX    = 8

INVALID_PARAM = -1