'''
Created on Feb 6, 2022

@author: Dream Machines
'''

# MIDI CC
MIDI_CC_SHIFT = 95
MIDI_CC_PLAY_STOP = 56
MIDI_CC_TEMPO = 94
MIDI_CC_LOOPER_VOLUME = 93
MIDI_CC_TRACK_VOLUME_1 = 16
MIDI_CH_TRACK_VOLUME_1 = 0
MIDI_CC_TRACK_VOLUME_2 = 17
MIDI_CH_TRACK_VOLUME_2 = 0
MIDI_CC_TRACK_VOLUME_3 = 18
MIDI_CH_TRACK_VOLUME_3 = 0
MIDI_CC_TRACK_VOLUME_4 = 19
MIDI_CH_TRACK_VOLUME_4 = 0

MIDI_CC_TRACK_MUTE_1 = 44
MIDI_CH_TRACK_MUTE_TRACK_1 = 0
MIDI_CC_TRACK_MUTE_2 = 45
MIDI_CH_TRACK_MUTE_TRACK_2 = 0
MIDI_CC_TRACK_MUTE_3 = 46
MIDI_CH_TRACK_MUTE_TRACK_3 = 0
MIDI_CC_TRACK_MUTE_4 = 47
MIDI_CH_TRACK_MUTE_TRACK_4 = 0

MIDI_CC_EXTRA_1 = 86
MIDI_CH_EXTRA_1 = 0

MIDI_CC_TRACK_PAN_1 = 16
MIDI_CH_TRACK_PAN_1 = 2
MIDI_CC_TRACK_PAN_2 = 17
MIDI_CH_TRACK_PAN_2 = 2
MIDI_CC_TRACK_PAN_3 = 18
MIDI_CH_TRACK_PAN_3 = 2
MIDI_CC_TRACK_PAN_4 = 19
MIDI_CH_TRACK_PAN_4 = 2

MIDI_CC_TRACK_RECORD_1 = 8
MIDI_CH_TRACK_RECORD_1 = 1
MIDI_CC_TRACK_RECORD_2 = 9
MIDI_CH_TRACK_RECORD_2 = 1
MIDI_CC_TRACK_RECORD_3 = 10
MIDI_CH_TRACK_RECORD_3 = 1
MIDI_CC_TRACK_RECORD_4 = 11
MIDI_CH_TRACK_RECORD_4 = 1

MIDI_CC_TRACK_CLEAR_1 = 12
MIDI_CH_TRACK_CLEAR_1 = 1
MIDI_CC_TRACK_CLEAR_2 = 13
MIDI_CH_TRACK_CLEAR_2 = 1
MIDI_CC_TRACK_CLEAR_3 = 14
MIDI_CH_TRACK_CLEAR_3 = 1
MIDI_CC_TRACK_CLEAR_4 = 15
MIDI_CH_TRACK_CLEAR_4 = 1

MIDI_CC_SAMPLE_LENGTH_1_64 = 85
MIDI_CH_SAMPLE_LENGTH_1_64 = 0
MIDI_CC_SAMPLE_LENGTH_1_32 = 84
MIDI_CH_SAMPLE_LENGTH_1_32 = 0
MIDI_CC_SAMPLE_LENGTH_1_16 = 83
MIDI_CH_SAMPLE_LENGTH_1_16 = 0
MIDI_CC_SAMPLE_LENGTH_1_8  = 82
MIDI_CH_SAMPLE_LENGTH_1_8  = 0
MIDI_CC_SAMPLE_LENGTH_1_4  = 81
MIDI_CH_SAMPLE_LENGTH_1_4  = 0
MIDI_CC_SAMPLE_LENGTH_1_2  = 80
MIDI_CH_SAMPLE_LENGTH_1_2  = 0
MIDI_CC_SAMPLE_LENGTH_1    = 72
MIDI_CH_SAMPLE_LENGTH_1    = 0
MIDI_CC_SAMPLE_LENGTH_2    = 73
MIDI_CH_SAMPLE_LENGTH_2    = 0
MIDI_CC_SAMPLE_LENGTH_4    = 74
MIDI_CH_SAMPLE_LENGTH_4    = 0
MIDI_CC_SAMPLE_LENGTH_8    = 75
MIDI_CH_SAMPLE_LENGTH_8    = 0
MIDI_CC_SAMPLE_LENGTH_16   = 76
MIDI_CH_SAMPLE_LENGTH_16   = 0
MIDI_CC_SAMPLE_LENGTH_32   = 77
MIDI_CH_SAMPLE_LENGTH_32   = 0
MIDI_CC_SAMPLE_LENGTH_64   = 78
MIDI_CH_SAMPLE_LENGTH_64   = 0
MIDI_CC_SAMPLE_LENGTH_128  = 79
MIDI_CH_SAMPLE_LENGTH_128  = 0

MIDI_CC_LOOPER_1 = 60
MIDI_CH_LOOPER_1 = 0
MIDI_CC_LOOPER_2 = 61
MIDI_CH_LOOPER_2 = 0
MIDI_CC_LOOPER_3 = 62
MIDI_CH_LOOPER_3 = 0
MIDI_CC_LOOPER_4 = 63
MIDI_CH_LOOPER_4 = 0

MIDI_CC_TRACK_SIDECHAIN_1 = 74
MIDI_CC_TRACK_SIDECHAIN_2 = 75
MIDI_CC_TRACK_SIDECHAIN_3 = 76
MIDI_CC_TRACK_SIDECHAIN_4 = 77
MIDI_CC_CLEAR_LOOPER = 55

MIDI_CC_RESAMPLE_MODE_FROM_LOOPER_TO_TRACK = 53
MIDI_CC_RESAMPLE_MODE_FROM_ALL_LOOPERS_TO_TRACK = 54

MIDI_CC_TURNADO_DICTATOR = 94
MIDI_CC_TURNADO_DRY_WET = 94

# ROUTING
MASTER_CHANNEL = 0
MASTER_FX_1_CHANNEL = 6
MIC_ROUTE_CHANNEL = 8
SYNTH_ROUTE_CHANNEL = 13
LOOPER_ALL_FX_1_CHANNEL = 22
LOOPERS_ALL_CHANNEL = 23
LOOPERS_ALL_WITHOUT_LEADS_CHANNEL = 24

LOOPER_1_FX_1_CHANNEL = 28
LOOPER_2_FX_1_CHANNEL = 36
LOOPER_3_FX_1_CHANNEL = 44
LOOPER_4_FX_1_CHANNEL = 52

LOOPER_1_CHANNEL = 26
LOOPER_2_CHANNEL = 34
LOOPER_3_CHANNEL = 42
LOOPER_4_CHANNEL = 50

LOOPER_1_INITIAL_TRACK_CHANNEL = 29
LOOPER_2_INITIAL_TRACK_CHANNEL = 37
LOOPER_3_INITIAL_TRACK_CHANNEL = 45
LOOPER_4_INITIAL_TRACK_CHANNEL = 53

LOOPER_1_SIDECHAIN_FILTER_FIRST_CHANNEL = 1
# CONSTANTS
TEMPO_JOG_ROTATION_THRESHOLD = 5

SHIFT_BUTTON_ON_DOUBLE_CLICK_SHIFT = 1000

DEFAULT_TURNADO_DRY_WET_LEVEL = 0.5

DEFAULT_TENSION_SIDECHAIN_LEVEL = 0.8
DEFAULT_DECAY_SIDECHAIN_LEVEL = 0.6

DEFAULT_AUDIO_ROUTING_LEVEL = 0.8

DEFAULT_SIDECHAIN_LEVEL = 0.1

# MASTER MIXER SLOT INDICES
MIDI_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 0
LOOPER_MUX_CONTROL_SURFACE_MIXER_SLOT_INDEX = 1
RESAMPLING_AUDIO_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 3

# MIXER SLOT INDICES
TRACK_AUGUSTUS_LOOP_PLUGIN_MIXER_SLOT_INDEX = 0
TRACK_PANOMATIC_PLUGIN_MIXER_SLOT_INDEX = 8
LOOPER_1_PEAK_CONTROLLER_SIDECHAIN_SLOT_INDEX = 7
LOOPER_ALL_ENDLESS_SMILE_SLOT_INDEX = 8

LOOPER_TURNADO_SLOT_INDEX = 0

# PLUGIN PARAMETERS

PEAK_CONTROLLER_BASE_PARAM_INDEX = 0
PEAK_CONTROLLER_VOLUME_PARAM_INDEX = 1
PEAK_CONTROLLER_TENSION_PARAM_INDEX = 2
PEAK_CONTROLLER_DECAY_PARAM_INDEX = 3

AUGUSTUS_LOOP_PLUGIN_MAX_DELAY_TIME_PARAM_INDEX = 0
AUGUSTUS_LOOP_PLUGIN_DELAY_TIME_PARAM_INDEX = 1
AUGUSTUS_LOOP_PLUGIN_DELAY_SLIDER_MIN_PARAM_INDEX = 2
AUGUSTUS_LOOP_PLUGIN_DELAY_SLIDER_MAX_PARAM_INDEX = 3
AUGUSTUS_LOOP_PLUGIN_LL_FEEDBACK_PARAM_INDEX = 5
AUGUSTUS_LOOP_PLUGIN_RR_FEEDBACK_PARAM_INDEX = 11
AUGUSTUS_LOOP_PLUGIN_MASTER_FEEDBACK_PARAM_INDEX = 12
AUGUSTUS_LOOP_PLUGIN_PITCH_INDEPENDENT_DELAY_PARAM_INDEX = 16
AUGUSTUS_LOOP_PLUGIN_EFFECT_LEVEL_PARAM_INDEX = 22
AUGUSTUS_LOOP_PLUGIN_INPUT_LEVEL_PARAM_INDEX = 31
AUGUSTUS_LOOP_PLUGIN_HOST_TEMPO_PARAM_INDEX = 33
AUGUSTUS_LOOP_PLUGIN_BEATS_PARAM_INDEX = 34
AUGUSTUS_LOOP_PLUGIN_BEATS_DIVISOR_PARAM_INDEX = 35
AUGUSTUS_LOOP_PLUGIN_CLEAR_LOOP_PARAM_INDEX = 49
AUGUSTUS_LOOP_PLUGIN_SATURATION_ON_OFF_PARAM_INDEX = 55
AUGUSTUS_LOOP_PLUGIN_DELAY_INTERIA_MODE_PARAM_INDEX = 57
AUGUSTUS_LOOP_PLUGIN_DIGITAL_MODE_PARAM_INDEX = 59
AUGUSTUS_LOOP_PLUGIN_SYNC_GROUP_MODE_PARAM_INDEX = 71

ENDLESS_SMILE_PLUGIN_INTENSITY_PARAM_INDEX = 0

PANOMATIC_VOLUME_PARAM_INDEX = 1
PANOMATIC_PAN_PARAM_INDEX = 0

TURNADO_DICTATOR_PARAM_INDEX = 8
TURNADO_DRY_WET_PARAM_INDEX = 9
TURNADO_RANDOMIZE_PARAM_INDEX = 10

Track_1 = 0
Track_2 = 1
Track_3 = 2
Track_4 = 3

Looper_1 = 0
Looper_2 = 1
Looper_3 = 2
Looper_4 = 3
