'''
Created on Feb 6, 2022

@author: Dream Machines
'''

from enum import IntEnum

# MIDI CC
MIDI_CC_TRACK_1_HP_FILTER = 24
MIDI_CH_TRACK_1_HP_FILTER = 0
MIDI_CC_TRACK_2_HP_FILTER = 25
MIDI_CH_TRACK_2_HP_FILTER = 0
MIDI_CC_TRACK_3_HP_FILTER = 26
MIDI_CH_TRACK_3_HP_FILTER = 0
MIDI_CC_TRACK_4_HP_FILTER = 27
MIDI_CH_TRACK_4_HP_FILTER = 0

MIDI_CC_TRACK_1_LP_FILTER = 24
MIDI_CH_TRACK_1_LP_FILTER = 2
MIDI_CC_TRACK_2_LP_FILTER = 25
MIDI_CH_TRACK_2_LP_FILTER = 2
MIDI_CC_TRACK_3_LP_FILTER = 26
MIDI_CH_TRACK_3_LP_FILTER = 2
MIDI_CC_TRACK_4_LP_FILTER = 27
MIDI_CH_TRACK_4_LP_FILTER = 2

MIDI_CC_LOOPER_MUTE_1 = 52
MIDI_CH_LOOPER_MUTE_1 = 0
MIDI_CC_LOOPER_MUTE_2 = 53
MIDI_CH_LOOPER_MUTE_2 = 0
MIDI_CC_LOOPER_MUTE_3 = 54
MIDI_CH_LOOPER_MUTE_3 = 0
MIDI_CC_LOOPER_MUTE_4 = 55
MIDI_CH_LOOPER_MUTE_4 = 0

MIDI_CC_LOOPER_MUTE_INVERTED_1 = 56
MIDI_CH_LOOPER_MUTE_INVERTED_1 = 0
MIDI_CC_LOOPER_MUTE_INVERTED_2 = 57
MIDI_CH_LOOPER_MUTE_INVERTED_2 = 0
MIDI_CC_LOOPER_MUTE_INVERTED_3 = 58
MIDI_CH_LOOPER_MUTE_INVERTED_3 = 0
MIDI_CC_LOOPER_MUTE_INVERTED_4 = 59
MIDI_CH_LOOPER_MUTE_INVERTED_4 = 0

MIDI_CC_TRACK_VOLUME_1 = 16
MIDI_CH_TRACK_VOLUME_1 = 0
MIDI_CC_TRACK_VOLUME_2 = 17
MIDI_CH_TRACK_VOLUME_2 = 0
MIDI_CC_TRACK_VOLUME_3 = 18
MIDI_CH_TRACK_VOLUME_3 = 0
MIDI_CC_TRACK_VOLUME_4 = 19
MIDI_CH_TRACK_VOLUME_4 = 0

MIDI_CC_TRACK_MUTE_1 = 44
MIDI_CH_TRACK_MUTE_1 = 0
MIDI_CC_TRACK_MUTE_2 = 45
MIDI_CH_TRACK_MUTE_2 = 0
MIDI_CC_TRACK_MUTE_3 = 46
MIDI_CH_TRACK_MUTE_3 = 0
MIDI_CC_TRACK_MUTE_4 = 47
MIDI_CH_TRACK_MUTE_4 = 0

MIDI_CC_TRACK_MUTE_INVERTED_1 = 48
MIDI_CH_TRACK_MUTE_INVERTED_1 = 0
MIDI_CC_TRACK_MUTE_INVERTED_2 = 49
MIDI_CH_TRACK_MUTE_INVERTED_2 = 0
MIDI_CC_TRACK_MUTE_INVERTED_3 = 50
MIDI_CH_TRACK_MUTE_INVERTED_3 = 0
MIDI_CC_TRACK_MUTE_INVERTED_4 = 51
MIDI_CH_TRACK_MUTE_INVERTED_4 = 0

MIDI_CC_EXTRA_1 = 86
MIDI_CH_EXTRA_1 = 0

MIDI_CC_TRACK_PAN_1 = 16
MIDI_CH_TRACK_PAN_1 = 2
MIDI_CC_TRACK_PAN_2 = 17
MIDI_CH_TRACK_PAN_2 = 2
MIDI_CC_TRACK_PAN_3 = 18
MIDI_CH_TRACK_PAN_3 = 2
MIDI_CC_TRACK_PAN_4 = 19
MIDI_CH_TRACK_PAN_4 = 2

MIDI_CC_TRACK_RECORD_1 = 8
MIDI_CH_TRACK_RECORD_1 = 1
MIDI_CC_TRACK_RECORD_2 = 9
MIDI_CH_TRACK_RECORD_2 = 1
MIDI_CC_TRACK_RECORD_3 = 10
MIDI_CH_TRACK_RECORD_3 = 1
MIDI_CC_TRACK_RECORD_4 = 11
MIDI_CH_TRACK_RECORD_4 = 1

MIDI_CC_TRACK_CLEAR_1 = 12
MIDI_CH_TRACK_CLEAR_1 = 1
MIDI_CC_TRACK_CLEAR_2 = 13
MIDI_CH_TRACK_CLEAR_2 = 1
MIDI_CC_TRACK_CLEAR_3 = 14
MIDI_CH_TRACK_CLEAR_3 = 1
MIDI_CC_TRACK_CLEAR_4 = 15
MIDI_CH_TRACK_CLEAR_4 = 1

MIDI_CC_SAMPLE_LENGTH_1_64 = 85
MIDI_CH_SAMPLE_LENGTH_1_64 = 0
MIDI_CC_SAMPLE_LENGTH_1_32 = 84
MIDI_CH_SAMPLE_LENGTH_1_32 = 0
MIDI_CC_SAMPLE_LENGTH_1_16 = 83
MIDI_CH_SAMPLE_LENGTH_1_16 = 0
MIDI_CC_SAMPLE_LENGTH_1_8  = 82
MIDI_CH_SAMPLE_LENGTH_1_8  = 0
MIDI_CC_SAMPLE_LENGTH_1_4  = 81
MIDI_CH_SAMPLE_LENGTH_1_4  = 0
MIDI_CC_SAMPLE_LENGTH_1_2  = 80
MIDI_CH_SAMPLE_LENGTH_1_2  = 0
MIDI_CC_SAMPLE_LENGTH_1    = 72
MIDI_CH_SAMPLE_LENGTH_1    = 0
MIDI_CC_SAMPLE_LENGTH_2    = 73
MIDI_CH_SAMPLE_LENGTH_2    = 0
MIDI_CC_SAMPLE_LENGTH_4    = 74
MIDI_CH_SAMPLE_LENGTH_4    = 0
MIDI_CC_SAMPLE_LENGTH_8    = 75
MIDI_CH_SAMPLE_LENGTH_8    = 0
MIDI_CC_SAMPLE_LENGTH_16   = 76
MIDI_CH_SAMPLE_LENGTH_16   = 0
MIDI_CC_SAMPLE_LENGTH_32   = 77
MIDI_CH_SAMPLE_LENGTH_32   = 0
MIDI_CC_SAMPLE_LENGTH_64   = 78
MIDI_CH_SAMPLE_LENGTH_64   = 0
MIDI_CC_SAMPLE_LENGTH_128  = 79
MIDI_CH_SAMPLE_LENGTH_128  = 0

MIDI_CC_LOOPER_1 = 60
MIDI_CH_LOOPER_1 = 0
MIDI_CC_LOOPER_2 = 61
MIDI_CH_LOOPER_2 = 0
MIDI_CC_LOOPER_3 = 62
MIDI_CH_LOOPER_3 = 0
MIDI_CC_LOOPER_4 = 63
MIDI_CH_LOOPER_4 = 0

MIDI_CC_TRACK_MUTE_1 = 44
MIDI_CH_TRACK_MUTE_1 = 0
MIDI_CC_TRACK_MUTE_2 = 45
MIDI_CH_TRACK_MUTE_2 = 0
MIDI_CC_TRACK_MUTE_3 = 46
MIDI_CH_TRACK_MUTE_3 = 0
MIDI_CC_TRACK_MUTE_4 = 47
MIDI_CH_TRACK_MUTE_4 = 0

MIDI_CC_CLEAR_LOOPER = 39
MIDI_CH_CLEAR_LOOPER = 1

MIDI_CC_CLEAR = 33
MIDI_CH_CLEAR = 0

MIDI_CC_START = 32
MIDI_CH_START = 0

MIDI_CC_TEMPO = 8
MIDI_CH_TEMPO = 0

MIDI_CC_SYNC_DAW_TRANSPORT = 8
MIDI_CH_SYNC_DAW_TRANSPORT = 2

MIDI_CC_TRACK_SIDECHAIN_1 = 74
MIDI_CC_TRACK_SIDECHAIN_2 = 75
MIDI_CC_TRACK_SIDECHAIN_3 = 76
MIDI_CC_TRACK_SIDECHAIN_4 = 77

MIDI_CC_RESAMPLE_MODE_FROM_LOOPER_TO_TRACK = 53
MIDI_CC_RESAMPLE_MODE_FROM_ALL_LOOPERS_TO_TRACK = 54

MIDI_CC_DROP        = 0
MIDI_CH_DROP        = 2
MIDI_CC_DROP_FX_1   = 0
MIDI_CH_DROP_FX_1   = 0
MIDI_CC_DROP_FX_2   = 1
MIDI_CH_DROP_FX_2   = 0
MIDI_CC_DROP_FX_3   = 1
MIDI_CH_DROP_FX_3   = 2
MIDI_CC_DROP_FX_4   = 2
MIDI_CH_DROP_FX_4   = 0
MIDI_CC_DROP_FX_5   = 2
MIDI_CH_DROP_FX_5   = 2
MIDI_CC_DROP_FX_6   = 3
MIDI_CH_DROP_FX_6   = 0
MIDI_CC_DROP_FX_7   = 3
MIDI_CH_DROP_FX_7   = 2

MIDI_CC_SIDECHAIN_T1         = 20
MIDI_CH_SIDECHAIN_T1         = 0
MIDI_CC_SIDECHAIN_T2         = 21
MIDI_CH_SIDECHAIN_T2         = 0
MIDI_CC_SIDECHAIN_T3         = 22
MIDI_CH_SIDECHAIN_T3         = 0
MIDI_CC_SIDECHAIN_T4         = 23
MIDI_CH_SIDECHAIN_T4         = 0
MIDI_CC_SIDECHAIN_STASH_T1   = 20
MIDI_CH_SIDECHAIN_STASH_T1   = 2
MIDI_CC_SIDECHAIN_STASH_T2   = 21
MIDI_CH_SIDECHAIN_STASH_T2   = 2
MIDI_CC_SIDECHAIN_STASH_T3   = 22
MIDI_CH_SIDECHAIN_STASH_T3   = 2
MIDI_CC_SIDECHAIN_STASH_T4   = 23
MIDI_CH_SIDECHAIN_STASH_T4   = 2
MIDI_CC_SIDECHAIN_DECAY_T1   = 28
MIDI_CH_SIDECHAIN_DECAY_T1   = 0
MIDI_CC_SIDECHAIN_DECAY_T2   = 29
MIDI_CH_SIDECHAIN_DECAY_T2   = 0
MIDI_CC_SIDECHAIN_DECAY_T3   = 30
MIDI_CH_SIDECHAIN_DECAY_T3   = 0
MIDI_CC_SIDECHAIN_DECAY_T4   = 31
MIDI_CH_SIDECHAIN_DECAY_T4   = 0
MIDI_CC_SIDECHAIN_TENSION_T1 = 28
MIDI_CH_SIDECHAIN_TENSION_T1 = 2
MIDI_CC_SIDECHAIN_TENSION_T2 = 29
MIDI_CH_SIDECHAIN_TENSION_T2 = 2
MIDI_CC_SIDECHAIN_TENSION_T3 = 30
MIDI_CH_SIDECHAIN_TENSION_T3 = 2
MIDI_CC_SIDECHAIN_TENSION_T4 = 31
MIDI_CH_SIDECHAIN_TENSION_T4 = 2

MIDI_CC_SELECT_T1 = 16
MIDI_CH_SELECT_T1 = 1
MIDI_CC_SELECT_T2 = 17
MIDI_CH_SELECT_T2 = 1
MIDI_CC_SELECT_T3 = 18
MIDI_CH_SELECT_T3 = 1
MIDI_CC_SELECT_T4 = 19
MIDI_CH_SELECT_T4 = 1

MIDI_CC_FX_SLOT_1  = 88
MIDI_CH_FX_SLOT_1  = 0
MIDI_CC_FX_SLOT_2  = 89
MIDI_CH_FX_SLOT_2  = 0
MIDI_CC_FX_SLOT_3  = 90
MIDI_CH_FX_SLOT_3  = 0
MIDI_CC_FX_SLOT_4  = 91
MIDI_CH_FX_SLOT_4  = 0
MIDI_CC_FX_SLOT_5  = 92
MIDI_CH_FX_SLOT_5  = 0
MIDI_CC_FX_SLOT_6  = 96
MIDI_CH_FX_SLOT_6  = 0
MIDI_CC_FX_SLOT_7  = 97
MIDI_CH_FX_SLOT_7  = 0
MIDI_CC_FX_SLOT_8  = 98
MIDI_CH_FX_SLOT_8  = 0
MIDI_CC_FX_SLOT_9  = 99
MIDI_CH_FX_SLOT_9  = 0
MIDI_CC_FX_SLOT_10 = 100
MIDI_CH_FX_SLOT_10 = 0

MIDI_CC_FX_BANK_1  = 93
MIDI_CH_FX_BANK_1  = 0
MIDI_CC_FX_BANK_2  = 94
MIDI_CH_FX_BANK_2  = 0
MIDI_CC_FX_BANK_3  = 95
MIDI_CH_FX_BANK_3  = 0
MIDI_CC_FX_BANK_4  = 101
MIDI_CH_FX_BANK_4  = 0
MIDI_CC_FX_BANK_5  = 102
MIDI_CH_FX_BANK_5  = 0

MIDI_CC_FX_ANIMATION_1  = 20
MIDI_CH_FX_ANIMATION_1  = 1
MIDI_CC_FX_ANIMATION_2  = 21
MIDI_CH_FX_ANIMATION_2  = 1
MIDI_CC_FX_ANIMATION_3  = 22
MIDI_CH_FX_ANIMATION_3  = 1
MIDI_CC_FX_ANIMATION_4  = 23
MIDI_CH_FX_ANIMATION_4  = 1
MIDI_CC_FX_ANIMATION_5  = 24
MIDI_CH_FX_ANIMATION_5  = 1
MIDI_CC_FX_ANIMATION_6  = 25
MIDI_CH_FX_ANIMATION_6  = 1
MIDI_CC_FX_ANIMATION_7  = 26
MIDI_CH_FX_ANIMATION_7  = 1
MIDI_CC_FX_ANIMATION_8  = 27
MIDI_CH_FX_ANIMATION_8  = 1

MIDI_CC_FX_X1 = 32
MIDI_CH_FX_X1 = 7
MIDI_CC_FX_Y1 = 33
MIDI_CH_FX_Y1 = 7
MIDI_CC_FX_X2 = 34
MIDI_CH_FX_X2 = 7
MIDI_CC_FX_Y2 = 35
MIDI_CH_FX_Y2 = 7

MIDI_CC_FX_DRY_WET                 = 4
MIDI_CH_FX_DRY_WET                 = 0
MIDI_CC_FX_DRY_WET_RESET           = 4
MIDI_CH_FX_DRY_WET_RESET           = 2
MIDI_CC_FX_EXTRA_PARAMETER_1       = 5
MIDI_CH_FX_EXTRA_PARAMETER_1       = 0
MIDI_CC_FX_EXTRA_PARAMETER_1_RESET = 5
MIDI_CH_FX_EXTRA_PARAMETER_1_RESET = 2

MIDI_CC_REPEATER_4    = 36
MIDI_CH_REPEATER_4    = 0
MIDI_CC_REPEATER_2    = 37
MIDI_CH_REPEATER_2    = 0
MIDI_CC_REPEATER_1    = 38
MIDI_CH_REPEATER_1    = 0
MIDI_CC_REPEATER_1_2  = 39
MIDI_CH_REPEATER_1_2  = 0
MIDI_CC_REPEATER_1_4  = 40
MIDI_CH_REPEATER_1_4  = 0
MIDI_CC_REPEATER_1_8  = 41
MIDI_CH_REPEATER_1_8  = 0
MIDI_CC_REPEATER_1_16 = 42
MIDI_CH_REPEATER_1_16 = 0
MIDI_CC_REPEATER_1_32 = 43
MIDI_CH_REPEATER_1_32 = 0

MIDI_CC_REMIXER_PLAY_ONESHOT_1 = 40
MIDI_CH_REMIXER_PLAY_ONESHOT_1 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_2 = 41
MIDI_CH_REMIXER_PLAY_ONESHOT_2 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_3 = 42
MIDI_CH_REMIXER_PLAY_ONESHOT_3 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_4 = 43
MIDI_CH_REMIXER_PLAY_ONESHOT_4 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_5 = 44
MIDI_CH_REMIXER_PLAY_ONESHOT_5 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_6 = 45
MIDI_CH_REMIXER_PLAY_ONESHOT_6 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_7 = 46
MIDI_CH_REMIXER_PLAY_ONESHOT_7 = 1
MIDI_CC_REMIXER_PLAY_ONESHOT_8 = 47
MIDI_CH_REMIXER_PLAY_ONESHOT_8 = 1

MIDI_CC_REMIXER_CLEAR_MODE = 127
MIDI_CH_REMIXER_CLEAR_MODE = 0

MIDI_CC_REMIXER_UNIT_MIC = 64
MIDI_CH_REMIXER_UNIT_MIC = 0
MIDI_CC_REMIXER_UNIT_SYNTH = 65
MIDI_CH_REMIXER_UNIT_SYNTH = 0
MIDI_CC_REMIXER_UNIT_LOOPERS_ALL = 66
MIDI_CH_REMIXER_UNIT_LOOPERS_ALL = 0
MIDI_CC_REMIXER_UNIT_LOOPER_1 = 68
MIDI_CH_REMIXER_UNIT_LOOPER_1 = 0
MIDI_CC_REMIXER_UNIT_LOOPER_2 = 69
MIDI_CH_REMIXER_UNIT_LOOPER_2 = 0
MIDI_CC_REMIXER_UNIT_LOOPER_3 = 70
MIDI_CH_REMIXER_UNIT_LOOPER_3 = 0
MIDI_CC_REMIXER_UNIT_LOOPER_4 = 71
MIDI_CH_REMIXER_UNIT_LOOPER_4 = 0

MIDI_CC_REMIXER_UNIT_FX_RESET_ALL_PARAMETERS = 121
MIDI_CH_REMIXER_UNIT_FX_RESET_ALL_PARAMETERS = 0
MIDI_CC_REMIXER_UNIT_FX_REVERSE = 122
MIDI_CH_REMIXER_UNIT_FX_REVERSE = 0
MIDI_CC_REMIXER_UNIT_FX_REVERB = 123
MIDI_CH_REMIXER_UNIT_FX_REVERB = 0
MIDI_CC_REMIXER_UNIT_FX_DELAY = 124
MIDI_CH_REMIXER_UNIT_FX_DELAY = 0
MIDI_CC_REMIXER_UNIT_FX_PHASER = 125
MIDI_CH_REMIXER_UNIT_FX_PHASER = 0
MIDI_CC_REMIXER_UNIT_FX_STEREO_ENHANCER = 126
MIDI_CH_REMIXER_UNIT_FX_STEREO_ENHANCER = 0

MIDI_CC_REMIXER_UNIT_FX_PITCH_SHIFT = 12
MIDI_CH_REMIXER_UNIT_FX_PITCH_SHIFT = 0
MIDI_CC_REMIXER_UNIT_FX_RESET_PITCH_SHIFT = 12
MIDI_CH_REMIXER_UNIT_FX_RESET_PITCH_SHIFT = 2
MIDI_CC_REMIXER_UNIT_FX_VOLUME = 10
MIDI_CH_REMIXER_UNIT_FX_VOLUME = 0
MIDI_CC_REMIXER_UNIT_FX_RESET_VOLUME = 10
MIDI_CH_REMIXER_UNIT_FX_RESET_VOLUME = 2
MIDI_CC_REMIXER_UNIT_FX_PAN = 11
MIDI_CH_REMIXER_UNIT_FX_PAN = 0
MIDI_CC_REMIXER_UNIT_FX_RESET_PAN = 11
MIDI_CH_REMIXER_UNIT_FX_RESET_PAN = 2
MIDI_CC_REMIXER_UNIT_FX_DISTORTION = 13
MIDI_CH_REMIXER_UNIT_FX_DISTORTION = 0
MIDI_CC_REMIXER_UNIT_FX_RESET_DISTORTION = 13
MIDI_CH_REMIXER_UNIT_FX_RESET_DISTORTION = 2
MIDI_CC_REMIXER_UNIT_FX_SIDECHAIN_1 = 14
MIDI_CH_REMIXER_UNIT_FX_SIDECHAIN_1 = 0
MIDI_CC_REMIXER_UNIT_FX_SIDECHAIN_1_MODE = 14
MIDI_CH_REMIXER_UNIT_FX_SIDECHAIN_1_MODE = 2
MIDI_CC_REMIXER_UNIT_FX_SIDECHAIN_2 = 15
MIDI_CH_REMIXER_UNIT_FX_SIDECHAIN_2 = 0
MIDI_CC_REMIXER_UNIT_FX_SIDECHAIN_2_MODE = 15
MIDI_CH_REMIXER_UNIT_FX_SIDECHAIN_2_MODE = 2

# ROUTING
MASTER_CHANNEL = 0
MASTER_FX_1_CHANNEL = 6
MIC_ROUTE_CHANNEL = 8
SYNTH_ROUTE_CHANNEL = 17
LOOPERS_ALL_FX_1_CHANNEL = 30
LOOPERS_ALL_CHANNEL = 31
LOOPERS_ALL_WITHOUT_LEADS_CHANNEL = 32

LOOPER_1_FX_1_CHANNEL = 36
LOOPER_2_FX_1_CHANNEL = 44
LOOPER_3_FX_1_CHANNEL = 52
LOOPER_4_FX_1_CHANNEL = 60

LOOPER_1_CHANNEL = 34
LOOPER_2_CHANNEL = 42
LOOPER_3_CHANNEL = 50
LOOPER_4_CHANNEL = 58

LOOPER_1_INITIAL_TRACK_CHANNEL = 37
LOOPER_2_INITIAL_TRACK_CHANNEL = 45
LOOPER_3_INITIAL_TRACK_CHANNEL = 53
LOOPER_4_INITIAL_TRACK_CHANNEL = 61

RECORDING_BUS_CHANNEL               = 26
RECORDING_BUS_FEEDBACK_LOOP_CHANNEL = 27

LOOPER_1_SIDECHAIN_FILTER_FIRST_CHANNEL = 1

FX_UNIT_IN_CHANNEL      = 69
FX_UNIT_BLOCK_1_CHANNEL = 71
FX_UNIT_BLOCK_2_CHANNEL = 72
FX_UNIT_BLOCK_3_CHANNEL = 73
FX_UNIT_BLOCK_4_CHANNEL = 74
FX_UNIT_BLOCK_5_CHANNEL = 75
FX_UNIT_OUT_CHANNEL     = 76

REMIXER_MIC_MIXER_CHANNEL = 80
REMIXER_SYNTH_MIXER_CHANNEL = 81
REMIXER_ALL_LOOPERS_MIXER_CHANNEL = 82
REMIXER_LOOPER_1_MIXER_CHANNEL = 83
REMIXER_LOOPER_2_MIXER_CHANNEL = 84
REMIXER_LOOPER_3_MIXER_CHANNEL = 85
REMIXER_LOOPER_4_MIXER_CHANNEL = 86

REMIXER_FX_1_MIXER_CHANNEL = 87
REMIXER_FX_2_MIXER_CHANNEL = 88

DROP_REVERB_MIXER_CHANNEL = 31
REPEATER_MIXER_CHANNEL = 78

# CONSTANTS
TEMPO_JOG_ROTATION_THRESHOLD = 5

DEFAULT_TURNADO_DRY_WET_LEVEL = 0.5

DEFAULT_TENSION_SIDECHAIN_LEVEL = 0.8
DEFAULT_DECAY_SIDECHAIN_LEVEL = 0.6

DEFAULT_AUDIO_ROUTING_LEVEL = 0.8

DEFAULT_SIDECHAIN_LEVEL = 0.1

MIN_TEMPO = 80
MAX_TEMPO = 180

# MASTER MIXER SLOT INDICES
MIDI_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 0

# MIXER SLOT INDICES
TRACK_AUGUSTUS_LOOP_PLUGIN_MIXER_SLOT_INDEX = 0
TRACK_PANOMATIC_PLUGIN_MIXER_SLOT_INDEX = 8
LOOPER_PANOMATIC_PLUGIN_MIXER_SLOT_INDEX = 9
LOOPER_1_PEAK_CONTROLLER_SIDECHAIN_SLOT_INDEX = 7
LOOPER_ALL_ENDLESS_SMILE_SLOT_INDEX = 8

LOOPER_TURNADO_SLOT_INDEX = 0

DROP_FX_1_MIXER_SLOT = 8
DROP_FX_2_MIXER_SLOT = 2
DROP_FX_3_MIXER_SLOT = 3
DROP_FX_4_MIXER_SLOT = 4
DROP_FX_5_MIXER_SLOT = 5
DROP_FX_6_MIXER_SLOT = 6
DROP_FX_7_MIXER_SLOT = 7

DROP_REVERB_MIXER_SLOT = 1
REPEATER_MIXER_SLOT = 0

TRACK_FILTER_SLOT_INDEX = 6

REMIXER_MIC_MIXER_SLOT = 0
REMIXER_SYNTH_MIXER_SLOT = 0
REMIXER_ALL_LOOPERS_MIXER_SLOT = 0
REMIXER_LOOPER_1_MIXER_SLOT = 0
REMIXER_LOOPER_2_MIXER_SLOT = 0
REMIXER_LOOPER_3_MIXER_SLOT = 0
REMIXER_LOOPER_4_MIXER_SLOT = 0
REMIXER_FX_TURNADO_MIXER_SLOT = 2
REMIXER_SC_LOW_FREQ_MIXER_SLOT = 3
REMIXER_SC_MID_FREQ_MIXER_SLOT = 4
REMIXER_SC_HIGH_FREQ_MIXER_SLOT = 5
REMIXER_SC_LOW_FREQ_TO_VOLUME_MIXER_SLOT = 6

# PLUGIN PARAMETERS

PEAK_CONTROLLER_BASE_PARAM_INDEX = 0
PEAK_CONTROLLER_VOLUME_PARAM_INDEX = 1
PEAK_CONTROLLER_TENSION_PARAM_INDEX = 2
PEAK_CONTROLLER_DECAY_PARAM_INDEX = 3

AUGUSTUS_LOOP_PLUGIN_MAX_DELAY_TIME_PARAM_INDEX = 0
AUGUSTUS_LOOP_PLUGIN_DELAY_TIME_PARAM_INDEX = 1
AUGUSTUS_LOOP_PLUGIN_DELAY_SLIDER_MIN_PARAM_INDEX = 2
AUGUSTUS_LOOP_PLUGIN_DELAY_SLIDER_MAX_PARAM_INDEX = 3
AUGUSTUS_LOOP_PLUGIN_LL_FEEDBACK_PARAM_INDEX = 5
AUGUSTUS_LOOP_PLUGIN_RR_FEEDBACK_PARAM_INDEX = 11
AUGUSTUS_LOOP_PLUGIN_MASTER_FEEDBACK_PARAM_INDEX = 12
AUGUSTUS_LOOP_PLUGIN_PITCH_INDEPENDENT_DELAY_PARAM_INDEX = 16
AUGUSTUS_LOOP_PLUGIN_EFFECT_LEVEL_PARAM_INDEX = 22
AUGUSTUS_LOOP_PLUGIN_INPUT_LEVEL_PARAM_INDEX = 31
AUGUSTUS_LOOP_PLUGIN_HOST_TEMPO_PARAM_INDEX = 33
AUGUSTUS_LOOP_PLUGIN_BEATS_PARAM_INDEX = 34
AUGUSTUS_LOOP_PLUGIN_BEATS_DIVISOR_PARAM_INDEX = 35
AUGUSTUS_LOOP_PLUGIN_CLEAR_LOOP_PARAM_INDEX = 49
AUGUSTUS_LOOP_PLUGIN_SATURATION_ON_OFF_PARAM_INDEX = 55
AUGUSTUS_LOOP_PLUGIN_DELAY_INTERIA_MODE_PARAM_INDEX = 57
AUGUSTUS_LOOP_PLUGIN_DIGITAL_MODE_PARAM_INDEX = 59
AUGUSTUS_LOOP_PLUGIN_SYNC_GROUP_MODE_PARAM_INDEX = 71

ENDLESS_SMILE_PLUGIN_INTENSITY_PARAM_INDEX = 0

PANOMATIC_VOLUME_PARAM_INDEX = 1
PANOMATIC_PAN_PARAM_INDEX = 0

TURNADO_DICTATOR_PARAM_INDEX = 8
TURNADO_DRY_WET_PARAM_INDEX = 9
TURNADO_RANDOMIZE_PARAM_INDEX = 10

TURNADO_CONTROL_PARAMETER_1 = 0
TURNADO_CONTROL_PARAMETER_2 = 1
TURNADO_CONTROL_PARAMETER_3 = 2
TURNADO_CONTROL_PARAMETER_4 = 3
TURNADO_CONTROL_PARAMETER_5 = 4
TURNADO_CONTROL_PARAMETER_6 = 5
TURNADO_CONTROL_PARAMETER_7 = 6
TURNADO_CONTROL_PARAMETER_8 = 7

TURNADO_FX1_DRY_WET_PARAM_INDEX = 16
TURNADO_FX2_DRY_WET_PARAM_INDEX = 45
TURNADO_FX3_DRY_WET_PARAM_INDEX = 74
TURNADO_FX4_DRY_WET_PARAM_INDEX = 103
TURNADO_FX5_DRY_WET_PARAM_INDEX = 132
TURNADO_FX6_DRY_WET_PARAM_INDEX = 161
TURNADO_FX7_DRY_WET_PARAM_INDEX = 190
TURNADO_FX8_DRY_WET_PARAM_INDEX = 219

TRACK_FILTER_HP_L_ON_PARAMETER_INDEX = 3
TRACK_FILTER_HP_L_FREQ_PARAMETER_INDEX = 4
TRACK_FILTER_HP_R_ON_PARAMETER_INDEX = 7
TRACK_FILTER_HP_R_FREQ_PARAMETER_INDEX = 8
TRACK_FILTER_LP_L_ON_PARAMETER_INDEX = 5
TRACK_FILTER_LP_L_FREQ_PARAMETER_INDEX = 6
TRACK_FILTER_LP_R_ON_PARAMETER_INDEX = 9
TRACK_FILTER_LP_R_FREQ_PARAMETER_INDEX = 10

CROSSFADE_LOOP_SYNTH_VOLUME_PARAM_INDEX  = 0
CROSSFADE_LOOP_SYNTH_DRY_WET_PARAM_INDEX = 39
CROSSFADE_LOOP_SYNTH_RECORD_PARAM_INDEX  = 37
CROSSFADE_LOOP_SYNTH_RECORD_MODE_PARAM_INDEX = 36
CROSSFADE_LOOP_SYNTH_BEAT_DIVISOR_PARAM_INDEX = 68
CROSSFADE_LOOP_SYNTH_BEATS_PARAM_INDEX = 67
CROSSFADE_LOOP_SYNTH_PLAY_POSITION_PARAM_INDEX = 3
CROSSFADE_LOOP_SYNTH_ATTACK_PARAM_INDEX = 7
CROSSFADE_LOOP_SYNTH_DECAY_PARAM_INDEX = 8
CROSSFADE_LOOP_SYNTH_SUSTAIN_PARAM_INDEX = 14
CROSSFADE_LOOP_SYNTH_RELEASE_PARAM_INDEX = 9
CROSSFADE_LOOP_SYNTH_USE_BEATS_PARAM_INDEX = 66
CROSSFADE_LOOP_SYNTH_CROSSFADE_PARAM_INDEX = 6

FORMULA_CONTROLLER_B_PARAM_INDEX = 1

Track_1 = 0
Track_2 = 1
Track_3 = 2
Track_4 = 3

Looper_1 = 0
Looper_2 = 1
Looper_3 = 2
Looper_4 = 3
LoopersAll = 4

RemixerSlot_1 = 0
RemixerSlot_2 = 1
RemixerSlot_3 = 2
RemixerSlot_4 = 3
RemixerSlot_5 = 4
RemixerSlot_6 = 5
RemixerSlot_7 = 6
RemixerSlot_8 = 7

ONESHOT_SAMPLER_1_REC_ON_OFF_PARAMETER_INDEX = 1
ONESHOT_SAMPLER_2_REC_ON_OFF_PARAMETER_INDEX = 2
ONESHOT_SAMPLER_3_REC_ON_OFF_PARAMETER_INDEX = 10
ONESHOT_SAMPLER_4_REC_ON_OFF_PARAMETER_INDEX = 11
ONESHOT_SAMPLER_5_REC_ON_OFF_PARAMETER_INDEX = 13
ONESHOT_SAMPLER_6_REC_ON_OFF_PARAMETER_INDEX = 12
ONESHOT_SAMPLER_7_REC_ON_OFF_PARAMETER_INDEX = 14
ONESHOT_SAMPLER_8_REC_ON_OFF_PARAMETER_INDEX = 15

ONESHOT_SAMPLER_1_VOLUME_PARAMETER_INDEX = 16
ONESHOT_SAMPLER_2_VOLUME_PARAMETER_INDEX = 17
ONESHOT_SAMPLER_3_VOLUME_PARAMETER_INDEX = 18
ONESHOT_SAMPLER_4_VOLUME_PARAMETER_INDEX = 19
ONESHOT_SAMPLER_5_VOLUME_PARAMETER_INDEX = 20
ONESHOT_SAMPLER_6_VOLUME_PARAMETER_INDEX = 21
ONESHOT_SAMPLER_7_VOLUME_PARAMETER_INDEX = 22
ONESHOT_SAMPLER_8_VOLUME_PARAMETER_INDEX = 23

ONESHOT_SAMPLER_1_DRY_LEVEL_PARAMETER_INDEX = 32
ONESHOT_SAMPLER_2_DRY_LEVEL_PARAMETER_INDEX = 33
ONESHOT_SAMPLER_3_DRY_LEVEL_PARAMETER_INDEX = 34
ONESHOT_SAMPLER_4_DRY_LEVEL_PARAMETER_INDEX = 35
ONESHOT_SAMPLER_5_DRY_LEVEL_PARAMETER_INDEX = 36
ONESHOT_SAMPLER_6_DRY_LEVEL_PARAMETER_INDEX = 37
ONESHOT_SAMPLER_7_DRY_LEVEL_PARAMETER_INDEX = 38
ONESHOT_SAMPLER_8_DRY_LEVEL_PARAMETER_INDEX = 39

class RemixerUnitType(IntEnum):
    NONE = -1
    MIC = 0
    SYNTH = 1
    LOOPER_1 = 2
    LOOPER_2 = 3
    LOOPER_3 = 4
    LOOPER_4 = 5
    LOOPERS_ALL = 6

class RemixerFXStatus(IntEnum):
    ENABLED = 0
    DISABLED = 1

REMIXER_NUMBER_OF_SLOTS = 8
REMIXER_UNIT_MIC_FIRST_SLOT_CHANNEL = 4
REMIXER_UNIT_SYNTH_FIRST_SLOT_CHANNEL = REMIXER_UNIT_MIC_FIRST_SLOT_CHANNEL + REMIXER_NUMBER_OF_SLOTS
REMIXER_LOOPER_1_INPUT_CHANNEL = REMIXER_UNIT_SYNTH_FIRST_SLOT_CHANNEL + REMIXER_NUMBER_OF_SLOTS
REMIXER_LOOPER_2_INPUT_CHANNEL = REMIXER_LOOPER_1_INPUT_CHANNEL + 1
REMIXER_LOOPER_3_INPUT_CHANNEL = REMIXER_LOOPER_2_INPUT_CHANNEL + 1
REMIXER_LOOPER_4_INPUT_CHANNEL = REMIXER_LOOPER_3_INPUT_CHANNEL + 1
REMIXER_LOOPERS_ALL_INPUT_CHANNEL = REMIXER_LOOPER_4_INPUT_CHANNEL + 1

DEFAULT_REMIXER_NOTE = 60

class RemixerFXSidechainItemType(IntEnum):
    LOW_FREQ = 0
    MID_FREQ = 1
    HIGH_FREQ = 2
    LOW_FREQ_TO_VOLUME = 3

class RemixerFXSidechainItemsPairMode(IntEnum):
    MODE_1 = 0
    MODE_2 = 1

class RemixerFXSidechainItemsPairType(IntEnum):
    PAIR_1 = 0
    PAIR_2 = 1