'''
Created on Feb 6, 2022

@author: Dream Machines
'''

# MIDI CC
MIDI_CC_LOOPER_VOLUME_1 = 24
MIDI_CH_LOOPER_VOLUME_1 = 0
MIDI_CC_LOOPER_VOLUME_2 = 25
MIDI_CH_LOOPER_VOLUME_2 = 0
MIDI_CC_LOOPER_VOLUME_3 = 26
MIDI_CH_LOOPER_VOLUME_3 = 0
MIDI_CC_LOOPER_VOLUME_4 = 27
MIDI_CH_LOOPER_VOLUME_4 = 0

MIDI_CC_LOOPER_MUTE_1 = 52
MIDI_CH_LOOPER_MUTE_1 = 0
MIDI_CC_LOOPER_MUTE_2 = 53
MIDI_CH_LOOPER_MUTE_2 = 0
MIDI_CC_LOOPER_MUTE_3 = 54
MIDI_CH_LOOPER_MUTE_3 = 0
MIDI_CC_LOOPER_MUTE_4 = 55
MIDI_CH_LOOPER_MUTE_4 = 0

MIDI_CC_TRACK_VOLUME_1 = 16
MIDI_CH_TRACK_VOLUME_1 = 0
MIDI_CC_TRACK_VOLUME_2 = 17
MIDI_CH_TRACK_VOLUME_2 = 0
MIDI_CC_TRACK_VOLUME_3 = 18
MIDI_CH_TRACK_VOLUME_3 = 0
MIDI_CC_TRACK_VOLUME_4 = 19
MIDI_CH_TRACK_VOLUME_4 = 0

MIDI_CC_TRACK_MUTE_1 = 44
MIDI_CH_TRACK_MUTE_1 = 0
MIDI_CC_TRACK_MUTE_2 = 45
MIDI_CH_TRACK_MUTE_2 = 0
MIDI_CC_TRACK_MUTE_3 = 46
MIDI_CH_TRACK_MUTE_3 = 0
MIDI_CC_TRACK_MUTE_4 = 47
MIDI_CH_TRACK_MUTE_4 = 0

MIDI_CC_EXTRA_1 = 86
MIDI_CH_EXTRA_1 = 0

MIDI_CC_TRACK_PAN_1 = 16
MIDI_CH_TRACK_PAN_1 = 2
MIDI_CC_TRACK_PAN_2 = 17
MIDI_CH_TRACK_PAN_2 = 2
MIDI_CC_TRACK_PAN_3 = 18
MIDI_CH_TRACK_PAN_3 = 2
MIDI_CC_TRACK_PAN_4 = 19
MIDI_CH_TRACK_PAN_4 = 2

MIDI_CC_TRACK_RECORD_1 = 8
MIDI_CH_TRACK_RECORD_1 = 1
MIDI_CC_TRACK_RECORD_2 = 9
MIDI_CH_TRACK_RECORD_2 = 1
MIDI_CC_TRACK_RECORD_3 = 10
MIDI_CH_TRACK_RECORD_3 = 1
MIDI_CC_TRACK_RECORD_4 = 11
MIDI_CH_TRACK_RECORD_4 = 1

MIDI_CC_TRACK_CLEAR_1 = 12
MIDI_CH_TRACK_CLEAR_1 = 1
MIDI_CC_TRACK_CLEAR_2 = 13
MIDI_CH_TRACK_CLEAR_2 = 1
MIDI_CC_TRACK_CLEAR_3 = 14
MIDI_CH_TRACK_CLEAR_3 = 1
MIDI_CC_TRACK_CLEAR_4 = 15
MIDI_CH_TRACK_CLEAR_4 = 1

MIDI_CC_SAMPLE_LENGTH_1_64 = 85
MIDI_CH_SAMPLE_LENGTH_1_64 = 0
MIDI_CC_SAMPLE_LENGTH_1_32 = 84
MIDI_CH_SAMPLE_LENGTH_1_32 = 0
MIDI_CC_SAMPLE_LENGTH_1_16 = 83
MIDI_CH_SAMPLE_LENGTH_1_16 = 0
MIDI_CC_SAMPLE_LENGTH_1_8  = 82
MIDI_CH_SAMPLE_LENGTH_1_8  = 0
MIDI_CC_SAMPLE_LENGTH_1_4  = 81
MIDI_CH_SAMPLE_LENGTH_1_4  = 0
MIDI_CC_SAMPLE_LENGTH_1_2  = 80
MIDI_CH_SAMPLE_LENGTH_1_2  = 0
MIDI_CC_SAMPLE_LENGTH_1    = 72
MIDI_CH_SAMPLE_LENGTH_1    = 0
MIDI_CC_SAMPLE_LENGTH_2    = 73
MIDI_CH_SAMPLE_LENGTH_2    = 0
MIDI_CC_SAMPLE_LENGTH_4    = 74
MIDI_CH_SAMPLE_LENGTH_4    = 0
MIDI_CC_SAMPLE_LENGTH_8    = 75
MIDI_CH_SAMPLE_LENGTH_8    = 0
MIDI_CC_SAMPLE_LENGTH_16   = 76
MIDI_CH_SAMPLE_LENGTH_16   = 0
MIDI_CC_SAMPLE_LENGTH_32   = 77
MIDI_CH_SAMPLE_LENGTH_32   = 0
MIDI_CC_SAMPLE_LENGTH_64   = 78
MIDI_CH_SAMPLE_LENGTH_64   = 0
MIDI_CC_SAMPLE_LENGTH_128  = 79
MIDI_CH_SAMPLE_LENGTH_128  = 0

MIDI_CC_LOOPER_1 = 60
MIDI_CH_LOOPER_1 = 0
MIDI_CC_LOOPER_2 = 61
MIDI_CH_LOOPER_2 = 0
MIDI_CC_LOOPER_3 = 62
MIDI_CH_LOOPER_3 = 0
MIDI_CC_LOOPER_4 = 63
MIDI_CH_LOOPER_4 = 0

MIDI_CC_TRACK_MUTE_1 = 44
MIDI_CH_TRACK_MUTE_1 = 0
MIDI_CC_TRACK_MUTE_2 = 45
MIDI_CH_TRACK_MUTE_2 = 0
MIDI_CC_TRACK_MUTE_3 = 46
MIDI_CH_TRACK_MUTE_3 = 0
MIDI_CC_TRACK_MUTE_4 = 47
MIDI_CH_TRACK_MUTE_4 = 0

MIDI_CC_CLEAR_LOOPER = 39
MIDI_CH_CLEAR_LOOPER = 1

MIDI_CC_CLEAR = 33
MIDI_CH_CLEAR = 0

MIDI_CC_START = 32
MIDI_CH_START = 0

MIDI_CC_TEMPO = 8
MIDI_CH_TEMPO = 0

MIDI_CC_SYNC_DAW_TRANSPORT = 8
MIDI_CH_SYNC_DAW_TRANSPORT = 2

MIDI_CC_TRACK_SIDECHAIN_1 = 74
MIDI_CC_TRACK_SIDECHAIN_2 = 75
MIDI_CC_TRACK_SIDECHAIN_3 = 76
MIDI_CC_TRACK_SIDECHAIN_4 = 77

MIDI_CC_RESAMPLE_MODE_FROM_LOOPER_TO_TRACK = 53
MIDI_CC_RESAMPLE_MODE_FROM_ALL_LOOPERS_TO_TRACK = 54

MIDI_CC_DROP        = 0
MIDI_CH_DROP        = 2
MIDI_CC_DROP_FX_1   = 0
MIDI_CH_DROP_FX_1   = 0
MIDI_CC_DROP_FX_2   = 1
MIDI_CH_DROP_FX_2   = 0
MIDI_CC_DROP_FX_3   = 1
MIDI_CH_DROP_FX_3   = 2
MIDI_CC_DROP_FX_4   = 2
MIDI_CH_DROP_FX_4   = 0
MIDI_CC_DROP_FX_5   = 2
MIDI_CH_DROP_FX_5   = 2
MIDI_CC_DROP_FX_6   = 3
MIDI_CH_DROP_FX_6   = 0
MIDI_CC_DROP_FX_7   = 3
MIDI_CH_DROP_FX_7   = 2

MIDI_CC_SIDECHAIN_T1         = 20
MIDI_CH_SIDECHAIN_T1         = 0
MIDI_CC_SIDECHAIN_T2         = 21
MIDI_CH_SIDECHAIN_T2         = 0
MIDI_CC_SIDECHAIN_T3         = 22
MIDI_CH_SIDECHAIN_T3         = 0
MIDI_CC_SIDECHAIN_T4         = 23
MIDI_CH_SIDECHAIN_T4         = 0
MIDI_CC_SIDECHAIN_STASH_T1   = 20
MIDI_CH_SIDECHAIN_STASH_T1   = 2
MIDI_CC_SIDECHAIN_STASH_T2   = 21
MIDI_CH_SIDECHAIN_STASH_T2   = 2
MIDI_CC_SIDECHAIN_STASH_T3   = 22
MIDI_CH_SIDECHAIN_STASH_T3   = 2
MIDI_CC_SIDECHAIN_STASH_T4   = 23
MIDI_CH_SIDECHAIN_STASH_T4   = 2
MIDI_CC_SIDECHAIN_DECAY_T1   = 28
MIDI_CH_SIDECHAIN_DECAY_T1   = 0
MIDI_CC_SIDECHAIN_DECAY_T2   = 29
MIDI_CH_SIDECHAIN_DECAY_T2   = 0
MIDI_CC_SIDECHAIN_DECAY_T3   = 30
MIDI_CH_SIDECHAIN_DECAY_T3   = 0
MIDI_CC_SIDECHAIN_DECAY_T4   = 31
MIDI_CH_SIDECHAIN_DECAY_T4   = 0
MIDI_CC_SIDECHAIN_TENSION_T1 = 28
MIDI_CH_SIDECHAIN_TENSION_T1 = 2
MIDI_CC_SIDECHAIN_TENSION_T2 = 29
MIDI_CH_SIDECHAIN_TENSION_T2 = 2
MIDI_CC_SIDECHAIN_TENSION_T3 = 30
MIDI_CH_SIDECHAIN_TENSION_T3 = 2
MIDI_CC_SIDECHAIN_TENSION_T4 = 31
MIDI_CH_SIDECHAIN_TENSION_T4 = 2

MIDI_CC_SELECT_T1 = 16
MIDI_CH_SELECT_T1 = 1
MIDI_CC_SELECT_T2 = 17
MIDI_CH_SELECT_T2 = 1
MIDI_CC_SELECT_T3 = 18
MIDI_CH_SELECT_T3 = 1
MIDI_CC_SELECT_T4 = 19
MIDI_CH_SELECT_T4 = 1

MIDI_CC_FX_SLOT_1  = 88
MIDI_CH_FX_SLOT_1  = 0
MIDI_CC_FX_SLOT_2  = 89
MIDI_CH_FX_SLOT_2  = 0
MIDI_CC_FX_SLOT_3  = 90
MIDI_CH_FX_SLOT_3  = 0
MIDI_CC_FX_SLOT_4  = 91
MIDI_CH_FX_SLOT_4  = 0
MIDI_CC_FX_SLOT_5  = 92
MIDI_CH_FX_SLOT_5  = 0
MIDI_CC_FX_SLOT_6  = 96
MIDI_CH_FX_SLOT_6  = 0
MIDI_CC_FX_SLOT_7  = 97
MIDI_CH_FX_SLOT_7  = 0
MIDI_CC_FX_SLOT_8  = 98
MIDI_CH_FX_SLOT_8  = 0
MIDI_CC_FX_SLOT_9  = 99
MIDI_CH_FX_SLOT_9  = 0
MIDI_CC_FX_SLOT_10 = 100
MIDI_CH_FX_SLOT_10 = 0

MIDI_CC_FX_BANK_1  = 93
MIDI_CH_FX_BANK_1  = 0
MIDI_CC_FX_BANK_2  = 94
MIDI_CH_FX_BANK_2  = 0
MIDI_CC_FX_BANK_3  = 95
MIDI_CH_FX_BANK_3  = 0
MIDI_CC_FX_BANK_4  = 101
MIDI_CH_FX_BANK_4  = 0
MIDI_CC_FX_BANK_5  = 102
MIDI_CH_FX_BANK_5  = 0

MIDI_CC_FX_ANIMATION_1  = 20
MIDI_CH_FX_ANIMATION_1  = 1
MIDI_CC_FX_ANIMATION_2  = 21
MIDI_CH_FX_ANIMATION_2  = 1
MIDI_CC_FX_ANIMATION_3  = 22
MIDI_CH_FX_ANIMATION_3  = 1
MIDI_CC_FX_ANIMATION_4  = 23
MIDI_CH_FX_ANIMATION_4  = 1
MIDI_CC_FX_ANIMATION_5  = 24
MIDI_CH_FX_ANIMATION_5  = 1
MIDI_CC_FX_ANIMATION_6  = 25
MIDI_CH_FX_ANIMATION_6  = 1
MIDI_CC_FX_ANIMATION_7  = 26
MIDI_CH_FX_ANIMATION_7  = 1
MIDI_CC_FX_ANIMATION_8  = 27
MIDI_CH_FX_ANIMATION_8  = 1

MIDI_CC_FX_X1 = 32
MIDI_CH_FX_X1 = 7
MIDI_CC_FX_Y1 = 33
MIDI_CH_FX_Y1 = 7
MIDI_CC_FX_X2 = 34
MIDI_CH_FX_X2 = 7
MIDI_CC_FX_Y2 = 35
MIDI_CH_FX_Y2 = 7

MIDI_CC_FX_DRY_WET                 = 4
MIDI_CH_FX_DRY_WET                 = 0
MIDI_CC_FX_DRY_WET_RESET           = 4
MIDI_CH_FX_DRY_WET_RESET           = 2
MIDI_CC_FX_EXTRA_PARAMETER_1       = 5
MIDI_CH_FX_EXTRA_PARAMETER_1       = 0
MIDI_CC_FX_EXTRA_PARAMETER_1_RESET = 5
MIDI_CH_FX_EXTRA_PARAMETER_1_RESET = 2

# ROUTING
MASTER_CHANNEL = 0
MASTER_FX_1_CHANNEL = 6
MIC_ROUTE_CHANNEL = 8
SYNTH_ROUTE_CHANNEL = 13
LOOPER_ALL_FX_1_CHANNEL = 22
LOOPERS_ALL_CHANNEL = 23
LOOPERS_ALL_FX_1_CHANNEL = 22
LOOPERS_ALL_WITHOUT_LEADS_CHANNEL = 24

LOOPER_1_FX_1_CHANNEL = 28
LOOPER_2_FX_1_CHANNEL = 36
LOOPER_3_FX_1_CHANNEL = 44
LOOPER_4_FX_1_CHANNEL = 52

LOOPER_1_CHANNEL = 26
LOOPER_2_CHANNEL = 34
LOOPER_3_CHANNEL = 42
LOOPER_4_CHANNEL = 50

LOOPER_1_INITIAL_TRACK_CHANNEL = 29
LOOPER_2_INITIAL_TRACK_CHANNEL = 37
LOOPER_3_INITIAL_TRACK_CHANNEL = 45
LOOPER_4_INITIAL_TRACK_CHANNEL = 53

RECORDING_BUS_CHANNEL               = 18
RECORDING_BUS_FEEDBACK_LOOP_CHANNEL = 19

LOOPER_1_SIDECHAIN_FILTER_FIRST_CHANNEL = 1

FX_UNIT_IN_CHANNEL      = 61
FX_UNIT_BLOCK_1_CHANNEL = 63
FX_UNIT_BLOCK_2_CHANNEL = 64
FX_UNIT_BLOCK_3_CHANNEL = 65
FX_UNIT_BLOCK_4_CHANNEL = 66
FX_UNIT_BLOCK_5_CHANNEL = 67
FX_UNIT_OUT_CHANNEL     = 68

# CONSTANTS
TEMPO_JOG_ROTATION_THRESHOLD = 5

DEFAULT_TURNADO_DRY_WET_LEVEL = 0.5

DEFAULT_TENSION_SIDECHAIN_LEVEL = 0.8
DEFAULT_DECAY_SIDECHAIN_LEVEL = 0.6

DEFAULT_AUDIO_ROUTING_LEVEL = 0.8

DEFAULT_SIDECHAIN_LEVEL = 0.1

MIN_TEMPO = 80
MAX_TEMPO = 180

# MASTER MIXER SLOT INDICES
MIDI_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 0

# MIXER SLOT INDICES
TRACK_AUGUSTUS_LOOP_PLUGIN_MIXER_SLOT_INDEX = 0
TRACK_PANOMATIC_PLUGIN_MIXER_SLOT_INDEX = 8
LOOPER_PANOMATIC_PLUGIN_MIXER_SLOT_INDEX = 9
LOOPER_1_PEAK_CONTROLLER_SIDECHAIN_SLOT_INDEX = 7
LOOPER_ALL_ENDLESS_SMILE_SLOT_INDEX = 8

LOOPER_TURNADO_SLOT_INDEX = 0

DROP_FX_1_MIXER_SLOT = 8
DROP_FX_2_MIXER_SLOT = 2
DROP_FX_3_MIXER_SLOT = 3
DROP_FX_4_MIXER_SLOT = 4
DROP_FX_5_MIXER_SLOT = 5
DROP_FX_6_MIXER_SLOT = 6
DROP_FX_7_MIXER_SLOT = 7

# PLUGIN PARAMETERS

PEAK_CONTROLLER_BASE_PARAM_INDEX = 0
PEAK_CONTROLLER_VOLUME_PARAM_INDEX = 1
PEAK_CONTROLLER_TENSION_PARAM_INDEX = 2
PEAK_CONTROLLER_DECAY_PARAM_INDEX = 3

AUGUSTUS_LOOP_PLUGIN_MAX_DELAY_TIME_PARAM_INDEX = 0
AUGUSTUS_LOOP_PLUGIN_DELAY_TIME_PARAM_INDEX = 1
AUGUSTUS_LOOP_PLUGIN_DELAY_SLIDER_MIN_PARAM_INDEX = 2
AUGUSTUS_LOOP_PLUGIN_DELAY_SLIDER_MAX_PARAM_INDEX = 3
AUGUSTUS_LOOP_PLUGIN_LL_FEEDBACK_PARAM_INDEX = 5
AUGUSTUS_LOOP_PLUGIN_RR_FEEDBACK_PARAM_INDEX = 11
AUGUSTUS_LOOP_PLUGIN_MASTER_FEEDBACK_PARAM_INDEX = 12
AUGUSTUS_LOOP_PLUGIN_PITCH_INDEPENDENT_DELAY_PARAM_INDEX = 16
AUGUSTUS_LOOP_PLUGIN_EFFECT_LEVEL_PARAM_INDEX = 22
AUGUSTUS_LOOP_PLUGIN_INPUT_LEVEL_PARAM_INDEX = 31
AUGUSTUS_LOOP_PLUGIN_HOST_TEMPO_PARAM_INDEX = 33
AUGUSTUS_LOOP_PLUGIN_BEATS_PARAM_INDEX = 34
AUGUSTUS_LOOP_PLUGIN_BEATS_DIVISOR_PARAM_INDEX = 35
AUGUSTUS_LOOP_PLUGIN_CLEAR_LOOP_PARAM_INDEX = 49
AUGUSTUS_LOOP_PLUGIN_SATURATION_ON_OFF_PARAM_INDEX = 55
AUGUSTUS_LOOP_PLUGIN_DELAY_INTERIA_MODE_PARAM_INDEX = 57
AUGUSTUS_LOOP_PLUGIN_DIGITAL_MODE_PARAM_INDEX = 59
AUGUSTUS_LOOP_PLUGIN_SYNC_GROUP_MODE_PARAM_INDEX = 71

ENDLESS_SMILE_PLUGIN_INTENSITY_PARAM_INDEX = 0

PANOMATIC_VOLUME_PARAM_INDEX = 1
PANOMATIC_PAN_PARAM_INDEX = 0

TURNADO_DICTATOR_PARAM_INDEX = 8
TURNADO_DRY_WET_PARAM_INDEX = 9
TURNADO_RANDOMIZE_PARAM_INDEX = 10

TURNADO_CONTROL_PARAMETER_1 = 0
TURNADO_CONTROL_PARAMETER_2 = 1
TURNADO_CONTROL_PARAMETER_3 = 2
TURNADO_CONTROL_PARAMETER_4 = 3
TURNADO_CONTROL_PARAMETER_5 = 4
TURNADO_CONTROL_PARAMETER_6 = 5
TURNADO_CONTROL_PARAMETER_7 = 6
TURNADO_CONTROL_PARAMETER_8 = 7

Track_1 = 0
Track_2 = 1
Track_3 = 2
Track_4 = 3

Looper_1 = 0
Looper_2 = 1
Looper_3 = 2
Looper_4 = 3
