'''
Created on Oct 7, 2023

@author: Dream Machines
'''

# CONSTANTS
REC_OFF                      = 62
REC_ON                       = 63

# MASTER MIXER SLOT INDICES
MIDI_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 0

# INSTRUMENT_SLOT_INDICES
CROSSFADE_LOOP_SYNTH_SLOT    = 3

# ROUTING
MASTER_CHANNEL               = 0
MIC_ROUTE_CHANNEL            = 4
SYNTH_INPUT_ROUTE_CHANNEL    = 10

# USED BASS STATION MIDI CC
NOVATION_REC_PRESSED                   = 81
NOVATION_ATTACK                        = 90
NOVATION_DECAY                         = 91
NOVATION_SUSTAIN                       = 92
NOVATION_RELEASE                       = 93
NOVATION_DISTORTION                    = 94
NOVATION_OSC_FILTER_MODE               = 115
NOVATION_MIXER_OSC_1                   = 20
NOVATION_MIXER_OSC_2                   = 21
NOVATION_FILTERS_MOD_ENV_DEPTH         = 85
NOVATION_FILTERS_LFO_2_DEPTH           = 17
NOVATION_IGNORED_1                     = 49
NOVATION_IGNORED_2                     = 52
NOVATION_IGNORED_3                     = 53
NOVATION_IGNORED_4                     = 56
NOVATION_MIXER_EXT_RING_NOISE          = 24
NOVATION_MIXER_SUB_OSC                 = 22

# PLUGIN PARAMETERS
CROSSFADE_LOOP_SYNTH_RECORD_PARAM_INDEX               = 37
CROSSFADE_LOOP_SYNTH_ATTACK_PARAM_INDEX               = 7
CROSSFADE_LOOP_SYNTH_DECAY_PARAM_INDEX                = 8
CROSSFADE_LOOP_SYNTH_SUSTAIN_PARAM_INDEX              = 14
CROSSFADE_LOOP_SYNTH_RELEASE_PARAM_INDEX              = 9
CROSSFADE_LOOP_SYNTH_LOOP_START_PARAM_INDEX           = 4
CROSSFADE_LOOP_SYNTH_LOOP_END_PARAM_INDEX             = 5
CROSSFADE_LOOP_SYNTH_SATURATION_AMOUNT_PARAM_INDEX    = 31
CROSSFADE_LOOP_SYNTH_SATURATION_SHAPE_PARAM_INDEX     = 32
CROSSFADE_LOOP_SYNTH_HARD_SYNC_CYCLE_PARAM_INDEX      = 79
CROSSFADE_LOOP_SYNTH_HARD_SYNC_DETUNE_PARAM_INDEX     = 80
CROSSFADE_LOOP_SYNTH_FEEDBACK_PARAM_INDEX             = 40
CROSSFADE_LOOP_SYNTH_VOLUME_PARAM_INDEX               = 0

