'''
Created on Oct 7, 2023

@author: Dream Machines
'''

# CONSTANTS
REC_OFF                      = 62
REC_ON                       = 63

# MASTER MIXER SLOT INDICES
MIDI_ROUTING_CONTROL_SURFACE_MIXER_SLOT_INDEX = 0

# INSTRUMENT_SLOT_INDICES
SYNTH_FEATURES_SLOT_INDEX                         = 5
SNAP_HEAP_SLOT_INDEX                              = 4
CROSSFADE_LOOP_SYNTH_SLOT_INDEX                   = 3
INPUT_CONTROLLER_PANOMATIC_SLOT_INDEX             = 2
INSTANT_SAMPLER_PANOMATIC_SLOT_INDEX              = 2
INSTANT_SAMPLER_SLOT_INDEX                        = 1

# ROUTING
MASTER_CHANNEL                   = 0
MIC_ROUTE_CHANNEL                = 8
SYNTH_ROUTE_CHANNEL              = 13
SYNTH_INPUT_ROUTE_CHANNEL        = 16
INSTANT_SAMPLER_SLOT_CHANNEL     = 58


# DEFAULT VALUES

CROSSFADE_LOOP_SYNTH_ATTACK_MIN_VALUE = 0.001
CROSSFADE_LOOP_SYNTH_ATTACK_DEFAULT_VALUE = CROSSFADE_LOOP_SYNTH_ATTACK_MIN_VALUE
CROSSFADE_LOOP_SYNTH_RELEASE_MIN_VALUE = 0.01
CROSSFADE_LOOP_SYNTH_RELEASE_DEFAULT_VALUE = CROSSFADE_LOOP_SYNTH_RELEASE_MIN_VALUE
CROSSFADE_LOOP_SYNTH_DECAY_MIN_VALUE = 0.01
CROSSFADE_LOOP_SYNTH_DECAY_DEFAULT_VALUE = 0.05
CROSSFADE_LOOP_SYNTH_SUSTAIN_DEFAULT_VALUE = 0

# USED BASS STATION MIDI CC
NOVATION_REC_PRESSED                   = 81
NOVATION_ATTACK                        = 90
NOVATION_DECAY                         = 91
NOVATION_SUSTAIN                       = 92
NOVATION_RELEASE                       = 93
NOVATION_DISTORTION                    = 94
NOVATION_OSC_FILTER_MODE               = 115
NOVATION_MIXER_OSC_1                   = 20
NOVATION_MIXER_OSC_2                   = 21
NOVATION_FILTERS_MOD_ENV_DEPTH         = 85
NOVATION_FILTERS_LFO_2_DEPTH           = 17
NOVATION_IGNORED_1                     = 49
NOVATION_IGNORED_2                     = 52
NOVATION_IGNORED_3                     = 53
NOVATION_IGNORED_4                     = 56
NOVATION_MIXER_EXT_RING_NOISE          = 24
NOVATION_MIXER_SUB_OSC                 = 22
NOVATION_SUB_OSC_WAVE                  = 80
NOVATION_MOD_WHEEL                     = 1
NOVATION_FILTERS_FREQUENCY             = 16
NOVATION_LFOS_LFO1_BTN                 = 88
NOVATION_LFOS_LFO2_BTN                 = 89
NOVATION_FILTERS_OVERRIDE              = 114
NOVATION_FILTERS_RESONANCE             = 82

# SNAP HEAD CONTROLS

NOVATION_OSCILLATORS_COARSE            = 27
NOVATION_OSCILLATORS_FINE              = 26
NOVATION_OSCILLATORS_MOD_ENV_DEPTH     = 71
NOVATION_OSCILLATORS_LFO_1_DEPTH       = 28
NOVATION_OSCILLATORS_PULSE_WIDTH       = 73
NOVATION_PORTA_GLIDE_TIME              = 5
NOVATION_LFOS_LFO1                     = 86
NOVATION_LFOS_LFO2                     = 87

# PLUGIN PARAMETERS
CROSSFADE_LOOP_SYNTH_RECORD_PARAM_INDEX               = 37
CROSSFADE_LOOP_SYNTH_ATTACK_PARAM_INDEX               = 7
CROSSFADE_LOOP_SYNTH_DECAY_PARAM_INDEX                = 8
CROSSFADE_LOOP_SYNTH_SUSTAIN_PARAM_INDEX              = 14
CROSSFADE_LOOP_SYNTH_RELEASE_PARAM_INDEX              = 9
CROSSFADE_LOOP_SYNTH_LOOP_START_PARAM_INDEX           = 4
CROSSFADE_LOOP_SYNTH_LOOP_END_PARAM_INDEX             = 5
CROSSFADE_LOOP_SYNTH_SATURATION_AMOUNT_PARAM_INDEX    = 31
CROSSFADE_LOOP_SYNTH_SATURATION_SHAPE_PARAM_INDEX     = 32
CROSSFADE_LOOP_SYNTH_HARD_SYNC_CYCLE_PARAM_INDEX      = 79
CROSSFADE_LOOP_SYNTH_HARD_SYNC_DETUNE_PARAM_INDEX     = 80
CROSSFADE_LOOP_SYNTH_FEEDBACK_PARAM_INDEX             = 40
CROSSFADE_LOOP_SYNTH_VOLUME_PARAM_INDEX               = 0
CROSSFADE_LOOP_SYNTH_BEAT_DIVISOR_PARAM_INDEX         = 68
CROSSFADE_LOOP_SYNTH_BEATS_PARAM_INDEX                = 67

SNAP_HEAP_MACRO_1_PARAM_INDEX = 25
SNAP_HEAP_MACRO_2_PARAM_INDEX = 26
SNAP_HEAP_MACRO_3_PARAM_INDEX = 27
SNAP_HEAP_MACRO_4_PARAM_INDEX = 28
SNAP_HEAP_MACRO_5_PARAM_INDEX = 29
SNAP_HEAP_MACRO_6_PARAM_INDEX = 30
SNAP_HEAP_MACRO_7_PARAM_INDEX = 31
SNAP_HEAP_MACRO_8_PARAM_INDEX = 32
SNAP_HEAP_DRY_WET_PARAM_INDEX = 145

PANOMATIC_PAN_PARAM_INDEX = 0
PANOMATIC_VOLUME_PARAM_INDEX = 1

INSTANT_SAMPLER_REVERSE_RANGE_PARAM_INDEX = 3
